# =================================================================
#
# Authors: doublebyte1 <jo@byteroad.net>>
#
# Copyright (c) 2025 doublebyte
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://localhost:5001
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        - pt-PT
        - en-US
    cors: true
    pretty_print: true
    limits:
        default_items: 20
        max_items: 50
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    admin: false # enable admin api

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            pt: Instância de defeito da pygeoapi
            en: pygeoapi default instance
        description:
            pt: A pygeoapi oferece uma API para dados geospaciais
            en: pygeoapi provides an API to geospatial data
        keywords:
            pt:
                - geospacial
                - dados
                - api
            en:
                - geospatial
                - data
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    distritos:
        type: collection
        title: CAOP2024 Distritos
        description: Carta Administrativa Oficial de Portugal, Continente, 2024. Distritos
        extents:
            spatial:
                bbox:
                - -9.51
                - 36.96
                - -6.19
                - 42.15
                crs: http://www.opengis.net/def/crs/EPSG/0/4326
        temporal:
            begin: 2000-10-30 18:24:39+00:00
            end: 2007-10-30 08:57:29+00:00
        keywords:
         - Limites Admnistrativos
         - Portugal Continental
         - Distritos
         - CAOP
        links:
        - href: https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/198497815bf647ecaa990c34c42e932e
          hreflang: en-US
          rel: canonical
          title: data
          type: text/csv

        providers:
            - type: feature
              name: SQLiteGPKG
              data: /data/cont_distritos.gpkg
              id_field: fid
              table: cont_distritos
            - type: tile
              name: MVT-tippecanoe
              data: /data/tiles/
              options:
                bounds: [[-9.51,36.96],[-6.19,42.15]]
                zoom:
                    min: 0
                    max: 11
              format: 
                    name: pbf
                    mimetype: application/vnd.mapbox-vector-tile
            - type: map
              name: WMSFacade
              data: https://geo2.dgterritorio.gov.pt/geoserver/caop_continente/wms
              options:
                    layer: cont_distritos
                    style: CAOP_Distrito
                    version: 1.3.0
              format:
                    name: png
                    mimetype: image/png

